# Generated by Django 2.2.4 on 2019-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_time_in_min', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_message', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('expiration', models.DateField()),
                ('member_id', models.CharField(max_length=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('px_expiration', models.CharField(default='Never', max_length=50)),
            ],
        ),
    ]
