# Generated by Django 2.2.4 on 2019-08-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='TransactionLogs',
        ),
    ]
