# Generated by Django 2.2.4 on 2019-08-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190825_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionLogs',
            new_name='TransactionLog',
        ),
    ]
