# Generated by Django 2.2.4 on 2019-08-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190825_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CUser',
        ),
    ]
