# Generated by Django 2.2.4 on 2019-08-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190825_0151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CUser',
            new_name='User',
        ),
    ]
